### PR TITLE
fix "Can't change username/password in web UI #6"

### PR DESCRIPTION
**Pull request by xerix32**
Fix https://github.com/gjroots/esp32_nat_router_plus/issues/6 bug

### CODE REVIEW

**Comment by gjroots** [comment]
I regret to inform you that I can't merge all of your pull requests due to the inclusion of static files in the commits. My concern is that this might cause confusion for other developers regarding the file changes. If there's only one file that has changes, a comment can help pinpoint the modifications in that file. However, I can definitely incorporate your code in the upcoming update.

Thank you being a part of development.... 😇

**Comment by xerix32** [comment]
> .. due to the inclusion of static files in the commits.
> Thank you being a part of development.... 😇

Sorry, I included gz files due to the presence of them in the repo (if someone doesn't have Jekyll full chain, there are necessary.)

But only this commit.

See you

**Comment by gjroots** [comment]
No problem, this isn't your error. I designed the project this way, but I might not have communicated it well. The main concept is that, if let's say only the info page has been modified, when you're making a commit, you should reverse the changes in all the other gz  files. This ensures that only the intended changes get committed, and the rest of the files remain unaffected.

So, dev's will understand what changes in which file easily.

**Comment by gjroots** [comment]
code merged with new release #15

Thank you for your contribution......

**Pull request closed without merging**
